### ISSUE TITLE
Seven digit postal codes for US addresses in patient addresses

### ISSUE THREAD

**Issue by mlos100** [intervention-engine/ptgen#11]
When I run generate (in tools project), the addresses for generated patients have 7 digit postal codes (e.g., 0733890)

**Comment by cmoesel** [comment]
Wow.  I never noticed that, but confirm that I see it as well.  [We're just using fake's `Zip()` function](https://github.com/intervention-engine/ptgen/blob/954757e11cf7458acacf7281bf147e4a2b4ddfc8/generate.go#L109), but it must default to some country that uses 7-digit zips.  I'll take a look at it.

**Comment by cmoesel** [comment]
Fixed in PR #12.
